name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set execute permissions
      run: chmod +x ./projectN/neuralNetwork.cpp
    - name: make
      run: make -C projectN
    - name: make check
      run: make -C projectN check
    - name: make distcheck
      run: make -C projectN distcheck
